# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/demo2_led/demo2_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led || ORIG_REF_NAME==demo2_led} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_zynq_ultra_ps_e_0_0/demo2_led_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==demo2_led_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_axi_timer_0_0/demo2_led_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_axi_timer_0_0 || ORIG_REF_NAME==demo2_led_axi_timer_0_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_axi_gpio_0_0/demo2_led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_0 || ORIG_REF_NAME==demo2_led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_axi_gpio_0_1/demo2_led_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_1 || ORIG_REF_NAME==demo2_led_axi_gpio_0_1} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_xbar_0/demo2_led_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_xbar_0 || ORIG_REF_NAME==demo2_led_xbar_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_auto_pc_0/demo2_led_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_auto_pc_0 || ORIG_REF_NAME==demo2_led_auto_pc_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_auto_pc_1/demo2_led_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_auto_pc_1 || ORIG_REF_NAME==demo2_led_auto_pc_1} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_ps8_0_axi_periph_0/demo2_led_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_ps8_0_axi_periph_0 || ORIG_REF_NAME==demo2_led_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_rst_ps8_0_99M_0/demo2_led_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_rst_ps8_0_99M_0 || ORIG_REF_NAME==demo2_led_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_ila_0_0/demo2_led_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_ila_0_0 || ORIG_REF_NAME==demo2_led_ila_0_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_jtag_axi_0_0/demo2_led_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_jtag_axi_0_0 || ORIG_REF_NAME==demo2_led_jtag_axi_0_0} -quiet] -quiet

# IP: bd/demo2_led/ip/demo2_led_system_ila_0_0/demo2_led_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_system_ila_0_0 || ORIG_REF_NAME==demo2_led_system_ila_0_0} -quiet] -quiet

# Block Designs: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/bd_c1e7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7 || ORIG_REF_NAME==bd_c1e7} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_0/bd_c1e7_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_ila_lib_0 || ORIG_REF_NAME==bd_c1e7_ila_lib_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_1/bd_c1e7_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_g_inst_0 || ORIG_REF_NAME==bd_c1e7_g_inst_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_2/bd_c1e7_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_slot_0_aw_0 || ORIG_REF_NAME==bd_c1e7_slot_0_aw_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_3/bd_c1e7_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_slot_0_w_0 || ORIG_REF_NAME==bd_c1e7_slot_0_w_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_4/bd_c1e7_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_slot_0_b_0 || ORIG_REF_NAME==bd_c1e7_slot_0_b_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_5/bd_c1e7_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_slot_0_ar_0 || ORIG_REF_NAME==bd_c1e7_slot_0_ar_0} -quiet] -quiet

# IP: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/ip/ip_6/bd_c1e7_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c1e7_slot_0_r_0 || ORIG_REF_NAME==bd_c1e7_slot_0_r_0} -quiet] -quiet

# Block Designs: bd/demo2_led_sim/demo2_led_sim.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim || ORIG_REF_NAME==demo2_led_sim} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_axi_vip_0_0/demo2_led_sim_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_axi_vip_0_0 || ORIG_REF_NAME==demo2_led_sim_axi_vip_0_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_axi_gpio_0_0/demo2_led_sim_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_axi_gpio_0_0 || ORIG_REF_NAME==demo2_led_sim_axi_gpio_0_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_axi_gpio_1_0/demo2_led_sim_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_axi_gpio_1_0 || ORIG_REF_NAME==demo2_led_sim_axi_gpio_1_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_xbar_0/demo2_led_sim_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_xbar_0 || ORIG_REF_NAME==demo2_led_sim_xbar_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_auto_pc_0/demo2_led_sim_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_auto_pc_0 || ORIG_REF_NAME==demo2_led_sim_auto_pc_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_axi_vip_0_axi_periph_0/demo2_led_sim_axi_vip_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_axi_vip_0_axi_periph_0 || ORIG_REF_NAME==demo2_led_sim_axi_vip_0_axi_periph_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_clk_wiz_0/demo2_led_sim_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_clk_wiz_0 || ORIG_REF_NAME==demo2_led_sim_clk_wiz_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_rst_clk_wiz_100M_0/demo2_led_sim_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_rst_clk_wiz_100M_0 || ORIG_REF_NAME==demo2_led_sim_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/demo2_led_sim/ip/demo2_led_sim_ila_0_0/demo2_led_sim_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_led_sim_ila_0_0 || ORIG_REF_NAME==demo2_led_sim_ila_0_0} -quiet] -quiet

# Block Designs: bd/demo1_ps_only/demo1_ps_only.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_ps_only || ORIG_REF_NAME==demo1_ps_only} -quiet] -quiet

# IP: bd/demo1_ps_only/ip/demo1_ps_only_zynq_ultra_ps_e_0_0/demo1_ps_only_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_ps_only_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==demo1_ps_only_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_zynq_ultra_ps_e_0_0/demo2_led_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_zynq_ultra_ps_e_0_0/demo2_led_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==demo2_led_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_timer_0_0/demo2_led_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_axi_timer_0_0 || ORIG_REF_NAME==demo2_led_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_timer_0_0/demo2_led_axi_timer_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_0/demo2_led_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_0 || ORIG_REF_NAME==demo2_led_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_0/demo2_led_axi_gpio_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_0/demo2_led_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_0 || ORIG_REF_NAME==demo2_led_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_1/demo2_led_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_1 || ORIG_REF_NAME==demo2_led_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_1/demo2_led_axi_gpio_0_1_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_axi_gpio_0_1/demo2_led_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_axi_gpio_0_1 || ORIG_REF_NAME==demo2_led_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_rst_ps8_0_99M_0/demo2_led_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_rst_ps8_0_99M_0 || ORIG_REF_NAME==demo2_led_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_rst_ps8_0_99M_0/demo2_led_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_rst_ps8_0_99M_0 || ORIG_REF_NAME==demo2_led_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_ila_0_0 || ORIG_REF_NAME==demo2_led_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_ila_0_0 || ORIG_REF_NAME==demo2_led_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_ila_0_0/demo2_led_ila_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_jtag_axi_0_0/constraints/jtag_axi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo2_led_jtag_axi_0_0 || ORIG_REF_NAME==demo2_led_jtag_axi_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/bd_0/bd_c1e7_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/ip/demo2_led_system_ila_0_0/demo2_led_system_ila_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led/demo2_led_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo2_led_sim/demo2_led_sim_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo1_ps_only/ip/demo1_ps_only_zynq_ultra_ps_e_0_0/demo1_ps_only_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo1_ps_only/ip/demo1_ps_only_zynq_ultra_ps_e_0_0/demo1_ps_only_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo1_ps_only_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==demo1_ps_only_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /local/d1/mcp011/demo2_led/project_1/project_1.gen/sources_1/bd/demo1_ps_only/demo1_ps_only_ooc.xdc
