# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.srcs/sources_1/ip/dataframe_fifo/dataframe_fifo.xci
# IP: The module: 'dataframe_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.srcs/sources_1/ip/dataframe_fifo/dataframe_fifo.xci
# IP: The module: 'dataframe_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /fasic_home/jchuenoh/fermi/spacely-caribou-common-blocks/pixel_buffer/vivado/data_frame_store/data_frame_store.gen/sources_1/ip/dataframe_fifo/dataframe_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataframe_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
