#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 09 15:54:19 CDT 2024
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim demo2_led_sim_tb_behav -key {Behavioral:sim_1:Functional:demo2_led_sim_tb} -tclbatch demo2_led_sim_tb.tcl -protoinst "protoinst_files/bd_c1e7.protoinst" -protoinst "protoinst_files/demo2_led.protoinst" -protoinst "protoinst_files/demo2_led_sim.protoinst" -protoinst "protoinst_files/demo1_ps_only.protoinst" -log simulate.log"
xsim demo2_led_sim_tb_behav -key {Behavioral:sim_1:Functional:demo2_led_sim_tb} -tclbatch demo2_led_sim_tb.tcl -protoinst "protoinst_files/bd_c1e7.protoinst" -protoinst "protoinst_files/demo2_led.protoinst" -protoinst "protoinst_files/demo2_led_sim.protoinst" -protoinst "protoinst_files/demo1_ps_only.protoinst" -log simulate.log

