# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.srcs/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0.xci
# IP: The module: 'configReg_interface_bd_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'configReg_interface_bd_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'configReg_interface_bd_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.srcs/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0.xci
# IP: The module: 'configReg_interface_bd_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'configReg_interface_bd_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/configReg_interface_bd/ip/configReg_interface_bd_auto_ds_0/configReg_interface_bd_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'configReg_interface_bd_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
