# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cms_pix_28_test_firmware.xdc

# Block Designs: bd/clock_wizard/clock_wizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard || ORIG_REF_NAME==clock_wizard} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_zynq_ultra_ps_e_0_0/clock_wizard_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==clock_wizard_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clock_wizard_clk_wiz_0_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_proc_sys_reset_0_0/clock_wizard_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_proc_sys_reset_0_0 || ORIG_REF_NAME==clock_wizard_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_axi_interconnect_0_0/clock_wizard_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_axi_interconnect_0_0 || ORIG_REF_NAME==clock_wizard_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_fw_top_v_0_0/clock_wizard_fw_top_v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_fw_top_v_0_0 || ORIG_REF_NAME==clock_wizard_fw_top_v_0_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_auto_ds_0/clock_wizard_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_auto_ds_0 || ORIG_REF_NAME==clock_wizard_auto_ds_0} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_auto_pc_0/clock_wizard_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_auto_pc_0 || ORIG_REF_NAME==clock_wizard_auto_pc_0} -quiet] -quiet

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/clock_wizard/clock_wizard_ooc.xdc
