# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cms_pix_28_test_firmware.xdc

# Block Designs: bd/cms_pix_28_fw_top_bd/cms_pix_28_fw_top_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd || ORIG_REF_NAME==cms_pix_28_fw_top_bd} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_zynq_ultra_ps_e_0_0/cms_pix_28_fw_top_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_proc_sys_reset_0_0/cms_pix_28_fw_top_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_axi_interconnect_0_0/cms_pix_28_fw_top_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_axi_interconnect_0_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_fw_top_v_0_0/cms_pix_28_fw_top_bd_fw_top_v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_fw_top_v_0_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_fw_top_v_0_0} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_auto_ds_0/cms_pix_28_fw_top_bd_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_auto_ds_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_auto_ds_0} -quiet] -quiet

# IP: bd/cms_pix_28_fw_top_bd/ip/cms_pix_28_fw_top_bd_auto_pc_0/cms_pix_28_fw_top_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_pix_28_fw_top_bd_auto_pc_0 || ORIG_REF_NAME==cms_pix_28_fw_top_bd_auto_pc_0} -quiet] -quiet

# XDC: /asic/projects/C/CMS_PIX_28/gingu/spacely/spacely-caribou-common-blocks/cms_pix_28_test_firmware/vivado/cms_pix_28_test_firmware.gen/sources_1/bd/cms_pix_28_fw_top_bd/cms_pix_28_fw_top_bd_ooc.xdc
