set_property PACKAGE_PIN W2 [get_ports SuperpixSel]
set_property PACKAGE_PIN V2 [get_ports ConfigClk]
set_property PACKAGE_PIN W1 [get_ports Reset_not]
set_property PACKAGE_PIN Y2 [get_ports ConfigIn]
set_property PACKAGE_PIN V1 [get_ports ConfigLoad]
set_property PACKAGE_PIN Y1 [get_ports ConfigOut]

set_property IOSTANDARD LVCMOS18 [get_ports SuperpixSel]
set_property IOSTANDARD LVCMOS18 [get_ports ConfigClk]
set_property IOSTANDARD LVCMOS18 [get_ports Reset_not]
set_property IOSTANDARD LVCMOS18 [get_ports ConfigIn]
set_property IOSTANDARD LVCMOS18 [get_ports ConfigLoad]
set_property IOSTANDARD LVCMOS18 [get_ports ConfigOut]